import Footer from './components/Footer'
import NavBar from './components/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import AuthContext from './context/AuthContext'
import DeckProvider from './context/DeckContext'
import FolderProvider from './context/FolderContext'
import Provider from './Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'QuizMe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <AuthContext>
            <DeckProvider>
              <FolderProvider>
                <NavBar />
                {children}
                <Footer />
              </FolderProvider>
            </DeckProvider>
          </AuthContext>
        </Provider>
      </body>
    </html>
  )
}
